# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'G-XJSGZSVTR3'

menu:
- {name: 'Products',          url: 'products'}
- {name: 'Docs',               url: 'docs'}
- {name: 'Careers',           url: 'https://www.linkedin.com/company/muddyterrain/jobs/'}
- {name: 'Support',           url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'x-twitter', link:    'https://x.com/muddyterrain'}
- {icon: 'instagram', link:  'https://instagram.com/muddyterrain'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/company/muddyterrain/'} 
- {icon: 'github',    link: 'https://github.com/muddyterrain'}
- {icon: 'envelope', link:   'mailto:mail@muddyterrain.com'}
- {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'discord', link: '/t/discord'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'Written on'

# Example Project Downloads
example_projects:
  - version: "5.6"
    cpp_link: "https://drive.google.com/file/d/1UJogx79EnU1AnOUUzfVVsrTEeEKendfj/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/10ZGj3hhE2nU0OQUOIKac0pGNbLZE0HeW/view?usp=drive_link"
  - version: "5.5"
    cpp_link: "https://drive.google.com/file/d/18Zzrmx3nzaQ8549QEMCz2HY1Atm_z8sa/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1wZRG4_E9d1-jNSV8Ar9n2oAu3NUKlHr4/view?usp=drive_link"
  - version: "5.4"
    cpp_link: "https://drive.google.com/file/d/10d8FFm57Wf9MoupWBlsn8IjEflZc0lYp/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1H4Y0Ot-AE-QQWMxrHavfGn0f9zXFrw-b/view?usp=drive_link"
  - version: "5.3"
    cpp_link: "https://drive.google.com/file/d/1AwCR1FAxMke9ns9BYGVXSMPADui8_IKz/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1b_SSq93SYsalWZFCnarfvOY401_BRtFZ/view?usp=drive_link"
  - version: "5.2"
    cpp_link: "https://drive.google.com/file/d/12Dv5EpJq4_OXnneb9l-AQ9VmlZCvSHS0/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1ZY6o7COF3stbjkzq0-ByJrNNngO2v6k4/view?usp=drive_link"
  - version: "5.1"
    cpp_link: "https://drive.google.com/file/d/1zYDn24wiIRzTI_lScSplHbSykyZWf2Pd/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1Bn3dZ9Z3-89L-IgwTXKhI6yImX07tKC6/view?usp=drive_link"

# Gen AI China Example Project Downloads
example_projects_china:
  - version: "5.6"
    bp_link: "https://drive.google.com/file/d/1e-b88lYxafqOCsfUqGdmNjDuFHqDL9to/view?usp=drive_link"
  - version: "5.5"
    bp_link: "https://drive.google.com/file/d/13-8zbN2kl_Fdgygo-VHKAby2jXqwSBpW/view?usp=drive_link"
  - version: "5.4"
    bp_link: "https://drive.google.com/file/d/1N2ZWhso5HLjFcnOogwRCtTuo0s79xVzX/view?usp=drive_link"
  - version: "5.3"
    bp_link: "https://drive.google.com/file/d/1KUdfZnNEGVpMR1pz4zsmqQsJFcIZM1UG/view?usp=drive_link"
  - version: "5.2"
    bp_link: "https://drive.google.com/file/d/1yiVoCGHDjvA8fkR_HsVUJc1_U3lrkGzI/view?usp=drive_link"
  - version: "5.1"
    bp_link: "https://drive.google.com/file/d/1K8oe_Z1feN7IpvVNaP6RiRn2y-h1OCUG/view?usp=drive_link"
