# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'G-XJSGZSVTR3'

menu:
- {name: 'Products',          url: 'products'}
- {name: 'Docs',               url: 'docs'}
- {name: 'Careers',           url: 'https://www.linkedin.com/company/muddyterrain/jobs/'}
- {name: 'Support',           url: 'contact'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'x-twitter', link:    'https://x.com/muddyterrain'}
- {icon: 'instagram', link:  'https://instagram.com/muddyterrain'}
- {icon: 'linkedin',  link: 'https://www.linkedin.com/company/muddyterrain/'} 
- {icon: 'github',    link: 'https://github.com/muddyterrain'}
- {icon: 'envelope', link:   'mailto:mail@muddyterrain.com'}
- {icon: 'rss-square', link: '/feed.xml'}
- {icon: 'discord', link: '/t/discord'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
# pagination:
#   next_page: 'Newer'
#   previous_page: 'Older'

# sharing_button_prompt: 'Feel free to share!'

# related_posts: 'You may also enjoy...'

# post_date_prefix: 'Written on'

# Example Project Downloads
example_projects:
  - version: "5.7"
    cpp_link: "https://drive.google.com/file/d/1FDWB9ObRwXesCg0SuxJntfuHr-8dHh3X/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1Mkdcozvy5LhU17MwGSOzF1bl_n-C78xc/view?usp=drive_link"
  - version: "5.6"
    cpp_link: "https://drive.google.com/file/d/1mveVquBOamcD5wkdLVhDJVt4DeJZyjxv/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1J4TkhAhVv8F-_-8oW6cqcstCLjPT4n-p/view?usp=drive_link"
  - version: "5.5"
    cpp_link: "https://drive.google.com/file/d/1Hw_0jNy-rxVcqx5aOr5bS2LHEJEfR6g1/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/10YCanG-NZ7RjOSQoBkqC4dV7XwiUueSz/view?usp=drive_link"
  - version: "5.4"
    cpp_link: "https://drive.google.com/file/d/10d8FFm57Wf9MoupWBlsn8IjEflZc0lYp/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1la0p0VkTOxKr2EDZ9eWMv0ebdsA-9mzM/view?usp=drive_link"
  - version: "5.3"
    cpp_link: "https://drive.google.com/file/d/1uhZsQVuyCWbesb7nRAaric6cqRaty0uu/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1APchMgg_gQgxXG7d4LxFsRyQh1c9NEXN/view?usp=drive_link"
  - version: "5.2"
    cpp_link: "https://drive.google.com/file/d/1eeRoPkFRApd5erFXvnXjij3u0CetyYKt/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1OgcAAk9EkAIduJKeH1GXzEc_cEy_HT9l/view?usp=drive_link"
  - version: "5.1"
    cpp_link: "https://drive.google.com/file/d/1esBHcaDkM6IHWt8wOA2ib_WK0HBpJgja/view?usp=drive_link"
    bp_link: "https://drive.google.com/file/d/1bN3eHRb9fA2cgcVTSuvF4nBj8WLcleAE/view?usp=drive_link"

# Gen AI China Example Project Downloads
example_projects_china:
  - version: "5.6"
    bp_link: "https://drive.google.com/file/d/1e-b88lYxafqOCsfUqGdmNjDuFHqDL9to/view?usp=drive_link"
  - version: "5.5"
    bp_link: "https://drive.google.com/file/d/13-8zbN2kl_Fdgygo-VHKAby2jXqwSBpW/view?usp=drive_link"
  - version: "5.4"
    bp_link: "https://drive.google.com/file/d/1N2ZWhso5HLjFcnOogwRCtTuo0s79xVzX/view?usp=drive_link"
  - version: "5.3"
    bp_link: "https://drive.google.com/file/d/1KUdfZnNEGVpMR1pz4zsmqQsJFcIZM1UG/view?usp=drive_link"
  - version: "5.2"
    bp_link: "https://drive.google.com/file/d/1yiVoCGHDjvA8fkR_HsVUJc1_U3lrkGzI/view?usp=drive_link"
  - version: "5.1"
    bp_link: "https://drive.google.com/file/d/1K8oe_Z1feN7IpvVNaP6RiRn2y-h1OCUG/view?usp=drive_link"
